name: Lint and Security Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-security:
    runs-on: ubuntu-20.04  # Changed to ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nbqa flake8 pylint bandit

      - name: Set up reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: v0.17.1

      - name: Check reviewdog version
        run: reviewdog -version

      - name: Run flake8 with reviewdog (notebooks)
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          nbqa flake8 . | reviewdog -f=flake8 -name="flake8 (nb)" -reporter=github-pr-review -filter_mode=added

      - name: Run flake8 with reviewdog (Python files)
        uses: reviewdog/action-flake8@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          flake8_flags: "--config=.flake8"
          filter_mode: added

      - name: Run pylint with reviewdog (notebooks)
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          nbqa pylint . --output-format=text | reviewdog -f=pylint -name="pylint (nb)" -reporter=github-pr-review -filter_mode=added

      - name: Run pylint with reviewdog (Python files)
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pylint --output-format=text --rcfile=.pylintrc . | reviewdog -f=pylint -name="pylint" -reporter=github-pr-review -filter_mode=added

      - name: Run bandit with reviewdog (notebooks)
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          nbqa bandit -r . | reviewdog -f=bandit -name="bandit (nb)" -reporter=github-pr-review -filter_mode=added

      - name: Run bandit with reviewdog (Python files)
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bandit -r . | reviewdog -f=bandit -name="bandit" -reporter=github-pr-review -filter_mode=added
